"""Aggregate panel results → data/validation_panel/REPORT.md.

Re-runs every panel case via pipeline.run, reads each certificate,
emits per-tactic AE distributions and a recommended bond-level AE
threshold τ.
"""
from __future__ import annotations

import json
import statistics
from pathlib import Path

from macrocert.pipeline import run


PANEL = Path("data/validation_panel")
REPORT = PANEL / "REPORT.md"


def _is_placeholder_case(case_dir: Path) -> bool:
    """Skip Workstream B placeholder cases (PLACEHOLDER MOL header or
    null ring_size in runspec). Same logic as tests/panel/test_panel.py.
    """
    mol = case_dir / "structure.mol"
    if mol.exists():
        try:
            if mol.read_text(encoding="utf-8", errors="replace").lstrip().startswith("# PLACEHOLDER"):
                return True
        except OSError:
            pass
    return False


def main():
    cases = sorted(d for d in PANEL.iterdir() if d.is_dir())
    results = []
    skipped = []
    for case_dir in cases:
        if not (case_dir / "runspec.yaml").exists():
            continue
        if _is_placeholder_case(case_dir):
            skipped.append(case_dir.name)
            continue
        report = run(case_dir, artifacts_dir="artifacts/panel")
        cert = json.loads(report.certificate_path.read_text())
        used = [
            cert["derivation_graph"]["hyperedges"][i]
            for i, e in enumerate(cert["derivation_graph"]["hyperedges"])
            if e["id"] in cert["flow"]
        ]
        rule_ids = {e["rule_id"] for e in used}
        results.append({
            "name": case_dir.name,
            "witness": report.witness_kind,
            "bond_AE": report.bond_level_expelled_mass,
            "process_AE": report.process_level_expelled_mass,
            "rule_ids": rule_ids,
            "ring_size": cert["derivation_graph"].get("max_steps"),
        })

    by_tactic: dict[str, list[float]] = {}
    for r in results:
        for rid in r["rule_ids"]:
            by_tactic.setdefault(rid, []).append(r["bond_AE"])

    lines = [
        "# Panel REPORT — calibration of AE threshold τ (v0)",
        "",
        f"Auto-generated by `pixi run python scripts/calibrate_panel.py` over "
        f"{len(results)} surrogate cases.",
        "",
        "## Per-case results",
        "",
        "| case | witness | bond AE (g/mol) | process AE (g/mol) | rule(s) |",
        "|------|---------|-----------------|--------------------|---------|",
    ]
    for r in results:
        lines.append(
            f"| {r['name']} | {r['witness']} | {r['bond_AE']:.2f} "
            f"| {r['process_AE']:.2f} | {', '.join(sorted(r['rule_ids']))} |"
        )

    lines += ["", "## Bond-level AE distribution by tactic", ""]
    for tactic, vals in sorted(by_tactic.items()):
        lines.append(f"### {tactic}")
        lines.append(f"  n = {len(vals)}; min = {min(vals):.2f}; max = "
                     f"{max(vals):.2f}; median = {statistics.median(vals):.2f} g/mol")
        lines.append("")

    if by_tactic:
        all_bond = [v for vs in by_tactic.values() for v in vs]
        tau_candidate = max(all_bond) + 1.0
        lines += [
            "## Recommended τ (v0)",
            "",
            f"Bond-level expelled-mass ceiling **τ = {tau_candidate:.2f} g/mol**",
            f"(maximum observed surrogate-case AE cost + 1 g/mol margin).",
            "",
            "All v0 surrogate cases close cleanly under this τ. Any candidate route",
            "with bond AE *above* this value is, by construction, worse than every",
            "case in this panel and should be reviewed as a candidate for",
            "infeasibility-certificate territory.",
            "",
            "Caveats:",
            "- Surrogate panel only — not the full literature panel (see panel_TODO.md).",
            "- TDA class (bond AE = 0) not represented in v0 — τ may be too loose",
            "  on the AE-optimal side when TDA literature cases land.",
            "- Process-level AE is *not* used to calibrate τ; the bond-vs-process",
            "  split is preserved per proposal §3.3, and each is reported separately.",
        ]

    if skipped:
        lines += [
            "",
            "## Skipped (placeholder structures)",
            "",
        ]
        for name in skipped:
            lines.append(f"- {name} — `structure.mol` is a `# PLACEHOLDER` awaiting Ivan's CIF audit")
        lines.append("")

    REPORT.write_text("\n".join(lines) + "\n")
    print(f"wrote {REPORT}")
    print(f"  {len(results)} cases summarized; {len(skipped)} skipped (placeholders); τ candidate documented")


if __name__ == "__main__":
    main()
